on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
name: release-then-publish
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: test-release-please
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - working-directory: ./packages/cyber-js-core
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - working-directory: ./packages/cyber-js-core
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      - working-directory: ./packages/cyber-js-core
        run: npm version ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
      - working-directory: ./packages/cyber-js-core
        run: npm publish --access public
        # TODO: --provenance doesn't seem to work in this context.
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}